### ISSUE TITLE
[BE] MockAPI를 통한 DB 설계 고민

### ISSUE THREAD

**Issue by guswns1659** [codesquad-member-2020/sidedish-04#5]

**Comment by haveagood** [comment]
<img width="1086" alt="스크린샷 2020-04-21 오후 6 38 59" src="https://user-images.githubusercontent.com/42365037/79850868-791c0500-83ff-11ea-91c0-f6636c59629f.png">

- Alex 1차 설계... 너무 복잡한건 아닌가 싶다.
